/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 25
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 27
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_segment = 1,
  sym_dollar = 2,
  sym_identifier = 3,
  anon_sym_DOLLAR = 4,
  anon_sym_COLON = 5,
  sym_group_segment = 6,
  anon_sym_BSLASH_LBRACE = 7,
  anon_sym_BSLASH_RBRACE = 8,
  anon_sym_BSLASH_BSLASH = 9,
  anon_sym_LBRACE = 10,
  anon_sym_RBRACE = 11,
  anon_sym_RBRACE_STAR = 12,
  anon_sym_RBRACE_PLUS = 13,
  anon_sym_RBRACE_QMARK = 14,
  anon_sym_RBRACE_BSLASH_STAR = 15,
  anon_sym_RBRACE_BSLASH_PLUS = 16,
  anon_sym_RBRACE_BSLASH_QMARK = 17,
  sym_source_file = 18,
  sym_literal = 19,
  sym_entry = 20,
  sym_variable_pattern = 21,
  sym_group_literal = 22,
  sym_group_pattern = 23,
  sym_pattern = 24,
  aux_sym_source_file_repeat1 = 25,
  aux_sym_group_pattern_repeat1 = 26,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_segment] = "segment",
  [sym_dollar] = "dollar",
  [sym_identifier] = "identifier",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_COLON] = ":",
  [sym_group_segment] = "group_segment",
  [anon_sym_BSLASH_LBRACE] = "\\{",
  [anon_sym_BSLASH_RBRACE] = "\\}",
  [anon_sym_BSLASH_BSLASH] = "\\\\",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_RBRACE_STAR] = "}*",
  [anon_sym_RBRACE_PLUS] = "}+",
  [anon_sym_RBRACE_QMARK] = "}\?",
  [anon_sym_RBRACE_BSLASH_STAR] = "}\\*",
  [anon_sym_RBRACE_BSLASH_PLUS] = "}\\+",
  [anon_sym_RBRACE_BSLASH_QMARK] = "}\\\?",
  [sym_source_file] = "source_file",
  [sym_literal] = "literal",
  [sym_entry] = "entry",
  [sym_variable_pattern] = "variable_pattern",
  [sym_group_literal] = "group_literal",
  [sym_group_pattern] = "group_pattern",
  [sym_pattern] = "pattern",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_group_pattern_repeat1] = "group_pattern_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_segment] = sym_segment,
  [sym_dollar] = sym_dollar,
  [sym_identifier] = sym_identifier,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_group_segment] = sym_group_segment,
  [anon_sym_BSLASH_LBRACE] = anon_sym_BSLASH_LBRACE,
  [anon_sym_BSLASH_RBRACE] = anon_sym_BSLASH_RBRACE,
  [anon_sym_BSLASH_BSLASH] = anon_sym_BSLASH_BSLASH,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_RBRACE_STAR] = anon_sym_RBRACE_STAR,
  [anon_sym_RBRACE_PLUS] = anon_sym_RBRACE_PLUS,
  [anon_sym_RBRACE_QMARK] = anon_sym_RBRACE_QMARK,
  [anon_sym_RBRACE_BSLASH_STAR] = anon_sym_RBRACE_BSLASH_STAR,
  [anon_sym_RBRACE_BSLASH_PLUS] = anon_sym_RBRACE_BSLASH_PLUS,
  [anon_sym_RBRACE_BSLASH_QMARK] = anon_sym_RBRACE_BSLASH_QMARK,
  [sym_source_file] = sym_source_file,
  [sym_literal] = sym_literal,
  [sym_entry] = sym_entry,
  [sym_variable_pattern] = sym_variable_pattern,
  [sym_group_literal] = sym_group_literal,
  [sym_group_pattern] = sym_group_pattern,
  [sym_pattern] = sym_pattern,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_group_pattern_repeat1] = aux_sym_group_pattern_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_segment] = {
    .visible = true,
    .named = true,
  },
  [sym_dollar] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_group_segment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BSLASH_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_BSLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_BSLASH_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_BSLASH_QMARK] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_group_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_group_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_group_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 9,
  [11] = 11,
  [12] = 12,
  [13] = 8,
  [14] = 14,
  [15] = 6,
  [16] = 7,
  [17] = 17,
  [18] = 17,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 22,
  [24] = 21,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      if (lookahead == '$') ADVANCE(11);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '}') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 1:
      if (lookahead == '$') ADVANCE(11);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == '}') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(14);
      END_STATE();
    case 2:
      if (lookahead == '$') ADVANCE(9);
      if (lookahead == '\\') ADVANCE(17);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '}') ADVANCE(16);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(23);
      if (lookahead == '+') ADVANCE(24);
      if (lookahead == '?') ADVANCE(25);
      END_STATE();
    case 4:
      if (eof) ADVANCE(5);
      if (lookahead == '$') ADVANCE(11);
      if (lookahead == '\\') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_segment);
      if (lookahead == '$') ADVANCE(9);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_segment);
      if (lookahead == '\\') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '$') ADVANCE(8);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_segment);
      if (lookahead != 0 &&
          lookahead != '$') ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_dollar);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_group_segment);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_group_segment);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_BSLASH_LBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_BSLASH_RBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_BSLASH_BSLASH);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      if (lookahead == '*') ADVANCE(20);
      if (lookahead == '+') ADVANCE(21);
      if (lookahead == '?') ADVANCE(22);
      if (lookahead == '\\') ADVANCE(3);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACE_STAR);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACE_PLUS);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RBRACE_QMARK);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RBRACE_BSLASH_STAR);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACE_BSLASH_PLUS);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACE_BSLASH_QMARK);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 4},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_dollar] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_BSLASH_LBRACE] = ACTIONS(1),
    [anon_sym_BSLASH_RBRACE] = ACTIONS(1),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_STAR] = ACTIONS(1),
    [anon_sym_RBRACE_PLUS] = ACTIONS(1),
    [anon_sym_RBRACE_QMARK] = ACTIONS(1),
    [anon_sym_RBRACE_BSLASH_STAR] = ACTIONS(1),
    [anon_sym_RBRACE_BSLASH_PLUS] = ACTIONS(1),
    [anon_sym_RBRACE_BSLASH_QMARK] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(20),
    [sym_literal] = STATE(11),
    [sym_variable_pattern] = STATE(13),
    [sym_group_pattern] = STATE(13),
    [sym_pattern] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_segment] = ACTIONS(5),
    [sym_dollar] = ACTIONS(5),
    [anon_sym_DOLLAR] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym_variable_pattern] = STATE(8),
    [sym_group_literal] = STATE(4),
    [sym_group_pattern] = STATE(8),
    [sym_pattern] = STATE(4),
    [aux_sym_group_pattern_repeat1] = STATE(4),
    [sym_dollar] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [sym_group_segment] = ACTIONS(13),
    [anon_sym_BSLASH_LBRACE] = ACTIONS(9),
    [anon_sym_BSLASH_RBRACE] = ACTIONS(9),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(15),
    [anon_sym_RBRACE_STAR] = ACTIONS(15),
    [anon_sym_RBRACE_PLUS] = ACTIONS(15),
    [anon_sym_RBRACE_QMARK] = ACTIONS(15),
    [anon_sym_RBRACE_BSLASH_STAR] = ACTIONS(15),
    [anon_sym_RBRACE_BSLASH_PLUS] = ACTIONS(15),
    [anon_sym_RBRACE_BSLASH_QMARK] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym_variable_pattern] = STATE(8),
    [sym_group_literal] = STATE(4),
    [sym_group_pattern] = STATE(8),
    [sym_pattern] = STATE(4),
    [aux_sym_group_pattern_repeat1] = STATE(4),
    [sym_dollar] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
    [sym_group_segment] = ACTIONS(13),
    [anon_sym_BSLASH_LBRACE] = ACTIONS(9),
    [anon_sym_BSLASH_RBRACE] = ACTIONS(9),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(17),
    [anon_sym_RBRACE_STAR] = ACTIONS(17),
    [anon_sym_RBRACE_PLUS] = ACTIONS(17),
    [anon_sym_RBRACE_QMARK] = ACTIONS(17),
    [anon_sym_RBRACE_BSLASH_STAR] = ACTIONS(17),
    [anon_sym_RBRACE_BSLASH_PLUS] = ACTIONS(17),
    [anon_sym_RBRACE_BSLASH_QMARK] = ACTIONS(17),
  },
  [STATE(4)] = {
    [sym_variable_pattern] = STATE(8),
    [sym_group_literal] = STATE(4),
    [sym_group_pattern] = STATE(8),
    [sym_pattern] = STATE(4),
    [aux_sym_group_pattern_repeat1] = STATE(4),
    [sym_dollar] = ACTIONS(19),
    [anon_sym_DOLLAR] = ACTIONS(22),
    [sym_group_segment] = ACTIONS(25),
    [anon_sym_BSLASH_LBRACE] = ACTIONS(19),
    [anon_sym_BSLASH_RBRACE] = ACTIONS(19),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(19),
    [anon_sym_RBRACE] = ACTIONS(28),
    [anon_sym_RBRACE_STAR] = ACTIONS(28),
    [anon_sym_RBRACE_PLUS] = ACTIONS(28),
    [anon_sym_RBRACE_QMARK] = ACTIONS(28),
    [anon_sym_RBRACE_BSLASH_STAR] = ACTIONS(28),
    [anon_sym_RBRACE_BSLASH_PLUS] = ACTIONS(28),
    [anon_sym_RBRACE_BSLASH_QMARK] = ACTIONS(28),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(32), 1,
      sym_group_segment,
    ACTIONS(30), 12,
      sym_dollar,
      anon_sym_DOLLAR,
      anon_sym_BSLASH_LBRACE,
      anon_sym_BSLASH_RBRACE,
      anon_sym_BSLASH_BSLASH,
      anon_sym_RBRACE,
      anon_sym_RBRACE_STAR,
      anon_sym_RBRACE_PLUS,
      anon_sym_RBRACE_QMARK,
      anon_sym_RBRACE_BSLASH_STAR,
      anon_sym_RBRACE_BSLASH_PLUS,
      anon_sym_RBRACE_BSLASH_QMARK,
  [18] = 2,
    ACTIONS(36), 1,
      sym_group_segment,
    ACTIONS(34), 12,
      sym_dollar,
      anon_sym_DOLLAR,
      anon_sym_BSLASH_LBRACE,
      anon_sym_BSLASH_RBRACE,
      anon_sym_BSLASH_BSLASH,
      anon_sym_RBRACE,
      anon_sym_RBRACE_STAR,
      anon_sym_RBRACE_PLUS,
      anon_sym_RBRACE_QMARK,
      anon_sym_RBRACE_BSLASH_STAR,
      anon_sym_RBRACE_BSLASH_PLUS,
      anon_sym_RBRACE_BSLASH_QMARK,
  [36] = 2,
    ACTIONS(40), 1,
      sym_group_segment,
    ACTIONS(38), 12,
      sym_dollar,
      anon_sym_DOLLAR,
      anon_sym_BSLASH_LBRACE,
      anon_sym_BSLASH_RBRACE,
      anon_sym_BSLASH_BSLASH,
      anon_sym_RBRACE,
      anon_sym_RBRACE_STAR,
      anon_sym_RBRACE_PLUS,
      anon_sym_RBRACE_QMARK,
      anon_sym_RBRACE_BSLASH_STAR,
      anon_sym_RBRACE_BSLASH_PLUS,
      anon_sym_RBRACE_BSLASH_QMARK,
  [54] = 2,
    ACTIONS(44), 1,
      sym_group_segment,
    ACTIONS(42), 12,
      sym_dollar,
      anon_sym_DOLLAR,
      anon_sym_BSLASH_LBRACE,
      anon_sym_BSLASH_RBRACE,
      anon_sym_BSLASH_BSLASH,
      anon_sym_RBRACE,
      anon_sym_RBRACE_STAR,
      anon_sym_RBRACE_PLUS,
      anon_sym_RBRACE_QMARK,
      anon_sym_RBRACE_BSLASH_STAR,
      anon_sym_RBRACE_BSLASH_PLUS,
      anon_sym_RBRACE_BSLASH_QMARK,
  [72] = 5,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      sym_group_segment,
    STATE(8), 2,
      sym_variable_pattern,
      sym_group_pattern,
    STATE(2), 3,
      sym_group_literal,
      sym_pattern,
      aux_sym_group_pattern_repeat1,
    ACTIONS(9), 4,
      sym_dollar,
      anon_sym_BSLASH_LBRACE,
      anon_sym_BSLASH_RBRACE,
      anon_sym_BSLASH_BSLASH,
  [94] = 5,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      sym_group_segment,
    STATE(8), 2,
      sym_variable_pattern,
      sym_group_pattern,
    STATE(3), 3,
      sym_group_literal,
      sym_pattern,
      aux_sym_group_pattern_repeat1,
    ACTIONS(9), 4,
      sym_dollar,
      anon_sym_BSLASH_LBRACE,
      anon_sym_BSLASH_RBRACE,
      anon_sym_BSLASH_BSLASH,
  [116] = 5,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
    ACTIONS(5), 2,
      sym_segment,
      sym_dollar,
    STATE(13), 2,
      sym_variable_pattern,
      sym_group_pattern,
    STATE(12), 3,
      sym_literal,
      sym_pattern,
      aux_sym_source_file_repeat1,
  [136] = 5,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      anon_sym_DOLLAR,
    ACTIONS(50), 2,
      sym_segment,
      sym_dollar,
    STATE(13), 2,
      sym_variable_pattern,
      sym_group_pattern,
    STATE(12), 3,
      sym_literal,
      sym_pattern,
      aux_sym_source_file_repeat1,
  [156] = 2,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    ACTIONS(42), 3,
      sym_segment,
      sym_dollar,
      anon_sym_DOLLAR,
  [165] = 2,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(58), 3,
      sym_segment,
      sym_dollar,
      anon_sym_DOLLAR,
  [174] = 2,
    ACTIONS(36), 1,
      ts_builtin_sym_end,
    ACTIONS(34), 3,
      sym_segment,
      sym_dollar,
      anon_sym_DOLLAR,
  [183] = 2,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
    ACTIONS(38), 3,
      sym_segment,
      sym_dollar,
      anon_sym_DOLLAR,
  [192] = 3,
    ACTIONS(60), 1,
      sym_identifier,
    ACTIONS(62), 1,
      anon_sym_LBRACE,
    STATE(21), 1,
      sym_entry,
  [202] = 3,
    ACTIONS(60), 1,
      sym_identifier,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    STATE(24), 1,
      sym_entry,
  [212] = 1,
    ACTIONS(66), 1,
      anon_sym_COLON,
  [216] = 1,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
  [220] = 1,
    ACTIONS(70), 1,
      anon_sym_COLON,
  [224] = 1,
    ACTIONS(72), 1,
      sym_identifier,
  [228] = 1,
    ACTIONS(74), 1,
      sym_identifier,
  [232] = 1,
    ACTIONS(76), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 18,
  [SMALL_STATE(7)] = 36,
  [SMALL_STATE(8)] = 54,
  [SMALL_STATE(9)] = 72,
  [SMALL_STATE(10)] = 94,
  [SMALL_STATE(11)] = 116,
  [SMALL_STATE(12)] = 136,
  [SMALL_STATE(13)] = 156,
  [SMALL_STATE(14)] = 165,
  [SMALL_STATE(15)] = 174,
  [SMALL_STATE(16)] = 183,
  [SMALL_STATE(17)] = 192,
  [SMALL_STATE(18)] = 202,
  [SMALL_STATE(19)] = 212,
  [SMALL_STATE(20)] = 216,
  [SMALL_STATE(21)] = 220,
  [SMALL_STATE(22)] = 224,
  [SMALL_STATE(23)] = 228,
  [SMALL_STATE(24)] = 232,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_group_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_group_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_group_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [28] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_group_pattern_repeat1, 2, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group_literal, 1, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group_literal, 1, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group_pattern, 4, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group_pattern, 4, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_pattern, 4, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_pattern, 4, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pattern, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pattern(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "pattern",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
